let gallery = [
    { id: 1, title: "Hospitality Spaces Painting", category: "Residential", content: "In Bicester, Oxford, we took on the challenge of painting a large family room designed to double as a hospitality space for events. The project required a high level of detail to ensure a welcoming ambiance. This project took 6 days and included prepping the walls, painting decorative trims, and ensuring the ceilings were flawless.", image: "/assets/Gallery/Gallery-Images.jpg" }, 
    { id: 2, title: "Pimlico Victoria Revamp", category: "Commercial", content: "In Pimlico Victoria, we revitalized a retail space by integrating contemporary design elements while preserving its historic charm. The challenge was balancing modern aesthetics with the building's architectural integrity. NewWalls successfully transformed the space, creating an inviting atmosphere that increased foot traffic and sales, showcasing our ability to blend innovation with tradition.", image: "/assets/Gallery/Gallery-Images-3.jpg" }, 
    { id: 3, title: "Banbury, Oxford Residential Makover", category: "Residential", content: "In Banbury, NewWalls completed a residential makeover that involved extensive interior painting and wallpapering. The challenge was to refresh the home while accommodating the client's specific design preferences. Our meticulous attention to detail resulted in a beautifully transformed living space that exceeded expectations, reflecting the homeowner's style and enhancing the overall ambiance of the property.", image: "/assets/Gallery/Gallery-Images-4.jpg" }, 
    { id: 4, title: "Brickwork Spray Coating", category: "Commercial", content: "In Richmond, London, we restored this home’s exterior with a protective spray coating. The project included treating the uPVC windows and frames for added durability and a fresh, unified appearance.", image: "/assets/Gallery/Gallery-Images-5.jpg" }, 
    { id: 5, title: "Garage Door Spraying", category: "Residential", content: "In Abingdon, Oxfordshire, we revitalized this garage door with a bold spray finish. We also treated the surrounding uPVC elements to ensure a seamless and weatherproof result.", image: "/assets/Gallery/Gallery-Images-6.jpg" }, 
    { id: 6, title: "Commercial Brick Restoration", category: "Commercial", content: "In Bloomsbury, London, we restored a historic office building with our specialist brick spraying service. The work included refinishing the uPVC windows and frames to ensure a cohesive and long-lasting result.", image: "/assets/Gallery/Gallery-Images-7.jpg" }, 
    { id: 7, title: "Feature Wall Design", category: "Residential", content: "In Shoreditch, London, we created a bold feature wall using textured spray finishes. The project also incorporated refinishing nearby uPVC trims, creating a polished, unified design", image: "/assets/Gallery/Gallery-Images-8.jpg" }, 
    { id: 8, title: "Curtain Wall Spraying", category: "Commercial", content: "In Canary Wharf, London, we enhanced this modern facade with our curtain wall spraying service. The project included treating uPVC frames to provide a sleek and weather-resistant finish.", image: "/assets/Gallery/Gallery-Images-9.jpg" }, 
    { id: 9, title: "Industrial Brick Restoration", category: "Commercial", content: "In Cowley, Oxford, we restored this industrial warehouse with our specialist brick spraying service. We also refreshed the uPVC window frames, adding durability and weather protection", image: "/assets/Gallery/Gallery-Images-10.jpg" }, 
    { id: 10, title: "Vehicle Restoration", category: "Commercial", content: "In Hackney, London, we revitalized a fleet of commercial vans with our precision spray painting service. The goal was to restore the vehicles' exteriors to a professional, brand-consistent finish. Newwalls delivered exceptional results that enhanced the fleet's appearance, showcasing our commitment to detail and durability.", image: "/assets/Gallery/Gallery-Images-11.jpg" }, 
    { id: 11, title: "Kitchen Spray Refresh", category: "Residential", content: "In Chelsea, London, we modernized this kitchen using our professional spray painting service. By applying a high-gloss finish to the cabinetry and uPVC surfaces, we created a sleek and durable space that added significant value to the home.", image: "/assets/Gallery/Gallery-Images-12.jpg" }, 
    { id: 12, title: "Exterior House Spraying", category: "Commercial", content: "In Headington, Oxford, we refreshed this home’s exterior using a vibrant spray coating. For a movie set our expertise extended to rejuvenating the uPVC elements, ensuring a cohesive, weather-resistant finish, exactly what the client wanted.", image: "/assets/Gallery/Gallery-Images-13.jpg" }, 
    { id: 13, title: "Door Transformation", category: "Commercial", content: "In Hackney, London, we enhanced this individual townhouse’s entrance for a film set with our spray painting service. By refreshing the uPVC door and windows with a weatherproof finish, we transformed the property’s look and feel.", image: "/assets/Gallery/Gallery-Images-14.jpg" }, 
    { id: 14, title: "Commercial Kitchen Upgrade", category: "Commercial", content: "In Oxford city center, we upgraded this busy kitchen with our durable spray coatings. By applying hygienic, heat-resistant finishes to walls and uPVC surfaces, we created a professional and functional space.", image: "/assets/Gallery/Gallery-Image-15.jpg" }
]